Basado en https://michielstock.github.io/posts/2022/2022-10-04-HDVtutorial/

In [37]:
import numpy as np
from numpy.typing import NDArray


In [38]:
N = 10000

def hdv() -> np.ndarray:
    return np.random.choice([-1, 1], size=N)

In [39]:
x = hdv()
x

array([-1, -1,  1, ...,  1,  1, -1])

In [40]:
y = hdv()
y

array([ 1,  1, -1, ...,  1, -1,  1])

In [41]:
np.sum(x == y)

4983

In [42]:
def hdv_m(rows: int) -> np.ndarray:
    return np.random.choice([-1, 1], size=(rows, N))

In [43]:
V = hdv_m(10)
V

array([[ 1,  1,  1, ..., -1,  1,  1],
       [ 1,  1,  1, ...,  1, -1,  1],
       [-1, -1,  1, ...,  1,  1,  1],
       ...,
       [-1,  1, -1, ..., -1,  1, -1],
       [ 1,  1,  1, ..., -1,  1, -1],
       [-1,  1, -1, ..., -1, -1,  1]])

## Bundling

In [44]:
def bundle_m(U: NDArray[int]) -> NDArray[int]:
    if U.ndim != 2:
        raise ValueError("U must be a 2d array.")

    return np.sign(np.sum(U, axis=0))

# ejemplo
U = np.array([[1, 2],
              [-3, 4],
              [5, -6]])

result = bundle_m(U)
print(result)

[1 0]


In [45]:
bundle_m(V)

array([ 0,  1,  0, ..., -1,  0,  0])

In [46]:
def bundle(*xs: NDArray[int]) -> NDArray[int]:
    summed = np.add.reduce(xs)
    return np.sign(summed)

# ejemplo
xs = bundle(np.array([1, 2]), np.array([-3, 4]), np.array([5, -6]))
print(xs)

[1 0]


In [48]:
bundle(x, y)

array([0, 0, 0, ..., 1, 0, 0])

## Binding

In [50]:
def bind(*xs: NDArray[int]):
    return np.multiply.reduce(xs)

# ejemplo
xs = bind(np.array([1, 2]), np.array([-3, 4]), np.array([5, -6]))
bind(xs)

array([-15, -48])

In [51]:
bind(x, y)

array([-1, -1, -1, ...,  1, -1, -1])

In [ ]:
np.array_equal(bind(bind(x, y), y), x)

True

In [56]:
np.array_equal(bind(bind(x, y), x), y)

True

## Shifting

In [57]:
def shift(x, k=1):
    return np.roll(x, k)

# ejemplo

shift([1, 2, 3])

array([3, 1, 2])

## Similarity between HDVs

In [ ]:
def cos_similarity(x, y):
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

# ejemplo
cos_similarity([1, 2, 3],
               [4, 5, 6])

0.9746318461970762

In [59]:
cos_similarity(x, y)

-0.0034

## Properties of the operations

In [60]:
z = hdv()

In [ ]:
np.array_equal(bind(x, bundle(y, z)),
               bundle(bind(x, y), bind(x, z)))

True

In [ ]:
np.array_equal(cos_similarity(x,y),
               cos_similarity(bind(x, z), bind(y, z)))

True